[GAMEPLAY]
; 游戏模式：survival(生存)、endless(无尽)、wilderness(荒野)
game_mode = survival

; 最大玩家数 64
max_players = 10

; 击剑模式      
pvp = false

; 没人玩的时候世界是否暂停(不暂停，直接饿死)
pause_when_empty = true

; 投票功能：true (开启，允许玩家在游戏里发起投票，比如回滚、重置世界)
vote_enabled = true

[NETWORK]
; 房间标签：cooperative (合作类型，方便别人筛选房间)
cluster_intention = cooperative

; 房间名字
cluster_name = 2026518

; 房间简介 
cluster_description = 电子阳阳的都在这

; 房间密码(不写就是公开房间)
cluster_password = 

; 自动存档
autosaver_enabled = true

; 投票踢人(不能通过投票踢人，只有管理员能踢)
enable_vote_kick = false

; 刷新率：官方默认 15。数字越高游戏越丝滑，但越吃配置和网络。
tick_rate = 15

; 连接超时时间(毫秒)如果玩家卡死断线超过设定秒，服务器就会把他踢掉腾位置。
connection_timeout = 80000

; 单机/离线模式，代码默认被注释。启用后，无需 Token，适用于局域网
; offline_server = false

[MISC]
; 存档快照数量：最多保留 6 个历史存档，用来在游戏里“回滚”天数
max_snapshots = 6

; 控制台：true (开启，允许管理员按 ~ 键输入指令/刷物品)
console_enabled = true

[STEAM]
; --- Steam 玩家管理 ---
; 填入你的 Steam 组 ID，加入该组的玩家可以在列表最上方看到你的服务器
; steam_group_id = 00000000000

; 如果设为 true，就只有这个 Steam 组的成员能进，相当于不用设密码的私密服
; steam_group_only = false

; 如果设为 true，Steam 组的管理在游戏里自动变成游戏管理员
; steam_group_admins = false

[SHARD]
; 通讯密钥：地上和地下服务器对暗号用的，默认即可
cluster_key = ThisIsTheSecretKeyForClusterCommunication

; 多世界联动：必须为 true，这样才能把地上和地下连起来
shard_enabled = true

; 绑定IP：0.0.0.0 代表接受来自任何地方的连接
bind_ip = 0.0.0.0

; 主世界IP：这里指定了 Docker 容器内部的连接地址
master_ip = dst_master